### ISSUE TITLE
a question, :-)

### ISSUE THREAD

**Issue by lzcchl** [lucastabelini/PolyLaneNet#1]
Hi, gratefully to share your project, and your models are so much, in what case run 115FPS, which backbone? what intput size? is that tusimple_320x180?

**Comment by lucastabelini** [comment]
The full model runs at 115 FPS on a Titan V. It uses EfficientNet-b0 as backbone with an input size of 640x360. The models `tusimple` and `tusimple_fulltrain` use those settings, the only difference is that the latter uses the full training set (train+val).
