### ISSUE TITLE
Can't visualize the output

### ISSUE THREAD

**Issue by pirate-lofy** [lucastabelini/PolyLaneNet#12]
Sorry if it seems a silly question, bu I do not know what should I do with the output.
I'm trying to predict the output of frames taken from video and the results are like this 
```
tensor([[ 1.5390e+01,  2.6866e-01,  5.9231e-01, -3.7041e-01,  5.3317e-01,
         -2.5742e-01,  4.1398e-01,  1.5413e+01, -7.1203e-03,  9.4199e-01,
         -5.6711e-01,  2.8064e-01,  8.4359e-02,  4.6005e-01, -2.2299e+01,
          1.8078e-03,  8.2544e-01,  1.4614e-01,  1.0139e-01, -2.6998e-01,
          5.8584e-01, -1.2889e+00,  1.7570e-02,  7.5274e-01,  9.5632e-02,
          7.7286e-02,  3.0168e-01,  3.6816e-01,  5.5416e-01,  7.4196e-02,
          7.2463e-01, -7.6063e-02, -1.3095e-01,  7.5693e-01,  3.2309e-01]],
       grad_fn=<AddmmBackward>)
```
I tried to draw these points with opencv's polylines but I couldn't.
Can you please tell me how to visualize the output

**Comment by lucastabelini** [comment]
You can use the `--view` flag in the `test.py` script to visualize the predictions. The code used to generate the visualization is [here](https://github.com/lucastabelini/PolyLaneNet/blob/ae8df40b32f819ba1ac480ed2c2ad1ccc35013a6/lib/datasets/lane_dataset.py#L98).
