### ISSUE TITLE
Suspect typo in the paper on arxiv

### ISSUE THREAD

**Issue by eeyrw** [lucastabelini/PolyLaneNet#14]
![image](https://user-images.githubusercontent.com/2088817/86126104-54838e00-bb10-11ea-81ff-32fd6afe596a.png)
I think the subscript here should be k=0.

**Comment by lucastabelini** [comment]
Thank you, you are correct. The paper will be updated soon on arXiv with other minor changes as well, since it got accepted at ICPR'20.

**Comment by eeyrw** [comment]
Got it : )

**Comment by mo-vic** [comment]
![image](https://user-images.githubusercontent.com/44632584/87397188-80117880-c5e6-11ea-8b89-f36b934f633f.png)

**Comment by lucastabelini** [comment]
Thank you for your input @mo-vic , but that is correct. The "[iff](https://en.wikipedia.org/wiki/If_and_only_if)" here means "if and only if".  What that sentence is trying to convey is: for any two lanes with indexes `j1` and `j2`, if and only if `j1 < j2`, then the point closest to the bottom of `j1` will have a smaller `x` value than the one in `j2`, which means that the lane `j1` is closer to the left border of the image.

**Comment by lucastabelini** [comment]
The paper has been updated on arXiv.
