### ISSUE TITLE
Urage For Help

### ISSUE THREAD

**Issue by AstoncPou** [lucastabelini/PolyLaneNet#15]
I just want to reproduce the exact reported metrics by testing the model;
it always shows the : **AttributeError: 'NoneType' object has no attribute 'shape'**
so maybe the code can't find the test image,so could tell me what's wrong with the below  ;
 I have download the dataset tusimple, there have two folder:test_set、train_set;
so i put the 0531 folder in the dataset folder(the 0531 file is from the test_set\clips\0531);
the detail is like that ：

├─cfgs
├─figures
├─datasets
│  └─tusimple
│      └─label_data_0531.json
│      └─0531
│    ──                └─1492626253262712112
│    ── ──                       └─1.jpg
│    ── ──                     └─2.jpg
│    ── ──                       └─......jpg
│    ── ──                     └─20.jpg
│   ──           └─1492626271917313999
│    ──          └─......
│   ──           └─1495489446318620134
├─experiments
├─lib
│  └─datasets
└─utils
└─test.py
└─train.py
└─config.yaml

and the root in config.yaml is that root: "datasets/tusimple"

**Comment by lucastabelini** [comment]
You should have a directory structure like that:
```
datasets/tusimple:
clips  label_data_0313.json  label_data_0531.json  label_data_0601.json  readme.md

datasets/tusimple-test:
clips readme.md  test_label.json  test_tasks_0627.json  test.txt
```

For the train split, if using this structure, the root in `config.yaml` should be `datasets/tusimple`, for the test split, `datasets/tusimple-test`.

**Comment by AstoncPou** [comment]
I'M trying with your advice, hope it can success
