### ISSUE TITLE
How do you arrange directory of dataset LLAMAS?

### ISSUE THREAD

**Issue by eeyrw** [lucastabelini/PolyLaneNet#16]
I have downloaded the dataset LLASMAS and there are two zip files: labels.zip and color_images.zip. It seems no official recommended way to organize directory. So what's your way to arrange directory?

**Comment by lucastabelini** [comment]
Create a directory to be the root of the dataset and then unzip both zips inside this directory. For example, if the root directory is `llamas`, the directory structure will be:
```
llamas
├── color_images
└── labels
```
