### ISSUE TITLE
Couldn't download models from Google Cloud in China.

### ISSUE THREAD

**Issue by meanmee** [lucastabelini/PolyLaneNet#26]
Could you upload the model up to github?

**Comment by lucastabelini** [comment]
The model files are too big, they might exceed GitHub's limit. Even if they don't, they would make the repository's size too large. Unfortunately, I don't have another host to use. 

Is it not possible to use a VPN?

**Comment by meanmee** [comment]
Most of the VPNs are blocked as far as I know.

**Comment by lucastabelini** [comment]
I can't see any viable alternatives for me. For now, I'm closing this issue.
