### ISSUE TITLE
Do I need to label lanes in a fixed order?

### ISSUE THREAD

**Issue by PJHardy** [lucastabelini/PolyLaneNet#28]
Thanks for your sharing.

Tusimple labeled 4 lanes for one image, and they have fixed order like left-left, ego-left, ego-right, right-right from 0 to 3.
Does the output of PolyLaneNet(L1 ~ L5) have the save order, or it just predict lane randomly?

If I want training my own dataset, do I need to label lanes in a fixed order?

**Comment by lucastabelini** [comment]
No, the code will sort the lanes for you ([here](https://github.com/lucastabelini/PolyLaneNet/blob/master/lib/datasets/lane_dataset.py#L69)).

**Comment by PJHardy** [comment]
So the targets  were sorted in this order, will the predicts of net obey this order?

When calculate loss you simply use MCE or BCE without any matching for targets and predicts, unlike the common object detection method, they usually need to find the connection between anchor and ground truth.

If  4 lanes are  labeled in a certain image and the predicts have 5 lanes,  it will just use the first 4 lanes of prediction to calculate loss(from [here](https://github.com/lucastabelini/PolyLaneNet/blob/9c7a447f5c2a69a24adb2b3910ff7154ce4e084b/lib/models.py#L97)). why does it work?

Another question, If I using tusimple dataset for training, can I just assume  the predicts (L1, L2, L3, L4) are exactly  (left-left, ego-left, ego-right, right-right)?

**Comment by lucastabelini** [comment]
> So the targets were sorted in this order, will the predicts of net obey this order?

Yes, probably.
> When calculate loss you simply use MCE or BCE without any matching for targets and predicts, unlike the common object detection method, they usually need to find the connection between anchor and ground truth.
>
> If 4 lanes are labeled in a certain image and the predicts have 5 lanes, it will just use the first 4 lanes of prediction to calculate loss(from [here](https://github.com/lucastabelini/PolyLaneNet/blob/9c7a447f5c2a69a24adb2b3910ff7154ce4e084b/lib/models.py#L97)). why does it work?

The model learns to predict all lanes in a sorted manner.

> Another question, If I using tusimple dataset for training, can I just assume the predicts (L1, L2, L3, L4) are exactly (left-left, ego-left, ego-right, right-right)?

Not sure. You would have to look at the dataset's original description.
