### ISSUE TITLE
Outputs

### ISSUE THREAD

**Issue by CQUTWRH** [lucastabelini/PolyLaneNet#30]
How can i get the outputs ?

**Comment by lucastabelini** [comment]
[Here](https://github.com/lucastabelini/PolyLaneNet/blob/master/test.py#L53).

**Comment by CQUTWRH** [comment]
Thanks for your guidance.        
I get this matrix.
        [[ 1.0000,  0.3513,  0.5950,  0.2744, -1.1041, -0.5563,  0.6782],
         [ 1.0000,  0.3513,  0.9942,  0.0537, -0.4085,  0.0901,  0.4443],
         [ 1.0000,  0.3513,  0.9506, -0.2649,  0.2023,  0.9700,  0.1097],
         [ 1.0000,  0.3513,  0.5977, -1.4024,  1.1435,  2.0329, -0.3219],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]

The sixth column represents the confidence score, if you follow your network.
But the confidence score has negative numbers and numbers greater than one.
I would be grateful if you could explain to me what this matrix means. 
：)

**Comment by lucastabelini** [comment]
Here's what each column stands for:
Column 0. Confidence score: It is not the raw value, because it is overwritten [here](https://github.com/lucastabelini/PolyLaneNet/blob/5e9a271734dea0c65b083c3ea1b347bf2ad65115/lib/models.py#L76).
Column 1. Top-y position (0 is top of the image and 1 is bottom)
Column 2. Bottom-y position
Column 3. y³ coefficient
Column 4. y² coefficient
Column 5. y¹ coefficient
Column 6. y⁰ coefficient

**Comment by CQUTWRH** [comment]
![outputs](https://user-images.githubusercontent.com/66502032/102438071-98366980-4056-11eb-85d8-ce399ccabcb9.png)

Can I get the confidence score on this picture ？

**Comment by lucastabelini** [comment]
What do you mean?

**Comment by CQUTWRH** [comment]
![figure](https://user-images.githubusercontent.com/66502032/102448057-3ed93500-406c-11eb-877b-ef7e2f8d4413.png)
C1, C2 and C3 in this figure

**Comment by lucastabelini** [comment]
I'm not sure if I understood you correctly, but, as I said in a previous message, the confidence score is the first column of the [outputs](https://github.com/lucastabelini/PolyLaneNet/blob/master/test.py#L53).

**Comment by CQUTWRH** [comment]
Thanks for your patient guidance  again！
