### ISSUE TITLE
Is it possible to detect lanes from a another point of view?

### ISSUE THREAD

**Issue by stah-ba** [lucastabelini/PolyLaneNet#31]
I would like to detect lanes in an image but not from the viewpoint of the moving car. For example, the lanes are horizontal in the image. Is this possible? Are there any restrictions implemented like the sorting of the lanes that prevent this task?

**Comment by lucastabelini** [comment]
Yes, there are restrictions. To detect lanes from another point of view would not be trivial.

**Comment by stah-ba** [comment]
Thanks for the answer.
But do you think your approach is conceivable for such an application? With some modifications. Or are the results achieved precisely because of the restrictions?

**Comment by lucastabelini** [comment]
Yes, I think it would work.

**Comment by stah-ba** [comment]
Thanks.

**Comment by aditbhrgv** [comment]
@stah-ba Have you managed to detect the horizontal lanes with this network ? Thanks in advance
