### ISSUE TITLE
Did you have a try to test in gray images on llamas datasets?

### ISSUE THREAD

**Issue by TTLL0928** [lucastabelini/PolyLaneNet#32]
Did you have a try to test in gray images on llamas datasets? Is there anything should be changed?

**Comment by lucastabelini** [comment]
No, I did not. I think you'll only need to change the number of input channels in the backbone.

**Comment by TTLL0928** [comment]
Hi, I have a try with llamas gray images with 10 epoch, however the result seems strange and I don't know why. Do you have email that I can send you the picture?

**Comment by lucastabelini** [comment]
It would be better if you attached the image here so that if others experience that problem they would know what to do.
