### ISSUE TITLE
Using the results of linear regression to train the model

### ISSUE THREAD

**Issue by gaopy3** [lucastabelini/PolyLaneNet#33]
Hi, thanks for your code! 

I noticed that the performance of the model is not as good as the performance of linear regression with the same MSE loss. 
Do they have any difference? 
Have you ever tried to let the model learn the coefficients(from linear regression) of polynomial directly？
(Although I think they should be the same.)

best regards

**Comment by lucastabelini** [comment]
> I noticed that the performance of the model is not as good as the performance of linear regression with the same MSE loss.
Do they have any difference?

I'm sorry, I don't understand.

> Have you ever tried to let the model learn the coefficients(from linear regression) of polynomial directly？
(Although I think they should be the same.)

Yes. The results were not very good as far as I remember.
