### ISSUE TITLE
regarding the dataloader

### ISSUE THREAD

**Issue by seyeeet** [lucastabelini/PolyLaneNet#38]
can you please explain the strategy behind this line of code?
[link](https://github.com/lucastabelini/PolyLaneNet/blob/master/lib/datasets/lane_dataset.py#L67) `lanes = np.ones((self.dataset.max_lanes, 1 + 2 + 2 * self.dataset.max_points), dtype=np.float32) * -1e5`
what/why we have `1`, and `2`,`2* self.dataset.max_points`? 
why do we multiply it with `* -1e5`?

**Comment by lucastabelini** [comment]
1 (confidence score) + 2 (bottom and top vertical positions) + 2 * max_points (a X and Y position for each point)
The array is multiplied with -1e5 just to make bug detection easier, it's just an in implementation detail. You can ignore it. In case the value is used somewhere it would be easier for me to debug. It is also used [here](https://github.com/lucastabelini/PolyLaneNet/blob/master/lib/models.py#L104).

**Comment by seyeeet** [comment]
Thank you for the explanation!
can you also tell me what `category` represent in the dataloader?

**Comment by lucastabelini** [comment]
It's the category of lane (e.g., dotted, dashed, etc). The only dataset I used that provides this information is ELAS. In the other datasets, the two categories are just positive (the lane exists) and negative (it doesn't).
