### ISSUE TITLE
About  image reading format when training

### ISSUE THREAD

**Issue by DCC-lzhy** [lucastabelini/PolyLaneNet#39]
In [https://github.com/lukemelas/EfficientNet-PyTorch](url), its image reading package is PIL.Image, and it's RGB mode.
But in your code, it's opencv-python and it's BGR mode.
I think it doesn't impact the final performance, whatever if use  the pretrained weights. And RGB reading mode will make training converge quickly.

**Comment by lucastabelini** [comment]
Yes, the image should be converted to RGB instead of BGR.
