### ISSUE TITLE
trouble in Reproducing the paper results

### ISSUE THREAD

**Issue by wq1148927746** [lucastabelini/PolyLaneNet#40]
Hello, my English level is very poor, I don't understand how to replace the parameter information in the text. Can you attach some pictures to it?

For example:

![image](https://user-images.githubusercontent.com/47206549/109938155-abc6a780-7d0a-11eb-9984-2a0779291479.png)

**Comment by lucastabelini** [comment]
Sorry, I don't know how to make it any more clear than the explanation in the picture.

**Comment by wq1148927746** [comment]
> Sorry, I don't know how to make it any more clear than the explanation in the picture.

Thanks for your answer. I think you can attach the example you used? That is, how did you run these codes step by step?

Thank you very much!

**Comment by lucastabelini** [comment]
Example from the `README.md` file:
```
python test.py --exp_name tusimple --cfg config.yaml --epoch 2695
```
Another one:
```
python test.py --exp_name tusimple --cfg experiments/tusimple/config.yaml --epoch 2695
```
In this example, `$exp_name=tusimple` and `$exps_dir=experiments`.

**Comment by wq1148927746** [comment]
> Example from the `README.md` file:
> 
> ```
> python test.py --exp_name tusimple --cfg config.yaml --epoch 2695
> ```
> 
> Another one:
> 
> ```
> python test.py --exp_name tusimple --cfg experiments/tusimple/config.yaml --epoch 2695
> ```
> 
> In this example, `$exp_name=tusimple` and `$exps_dir=experiments`.

Thank you very much! I will try again.
