### ISSUE TITLE
A problem about modify polynomial degree

### ISSUE THREAD

**Issue by NARRZ** [lucastabelini/PolyLaneNet#41]
Congratulations on your great achievements, I am a beginner and I am very interested in your results. I want to reproduce the data in your paper. If I want to modify the polynomial degree, where should I modify it?  Thank you very much.

**Comment by lucastabelini** [comment]
The key in the config file to be modified is `curriculum_steps`. I explained how that works [here](https://github.com/lucastabelini/PolyLaneNet/issues/29#issuecomment-733018419). Also, in the `cfgs` directory there are three different configs with polynomials of first, second and third order (e.g., `tusimple_1order,yaml`).

**Comment by NARRZ** [comment]
Thank you very much.I solved the problem under your suggestion.I want to ask how to draw the training curve and what are the specific commands.Looking forward to your reply.

**Comment by lucastabelini** [comment]
I will assume that by "training curve" you meant the loss curve. You can use the `utils/plot_log.py` script for that.

**Comment by k-nayak** [comment]
@NARRZ and @lucastabelini I was looking for a deep learning model that can compute Lanes and their curvature in real-time and based on the image results I was interested in this implementation, May I know if I can use this for real-time Lane and curvature detection? I plan on using such approaches inside Carla Simulator. I hope to hear from you soon. Thanks.
