### ISSUE TITLE
problem in code

### ISSUE THREAD

**Issue by wq1148927746** [lucastabelini/PolyLaneNet#42]
I'm here to bother again. I would like to ask what the following thresholds mean? What is the difference and connection between this and the confidence score threshold 0.5 mentioned in the article?

lib.models: line 91

![image](https://user-images.githubusercontent.com/47206549/110309194-ffebc780-803b-11eb-954a-31bf2f936e9a.png)

Thanks.

**Comment by lucastabelini** [comment]
This value corresponds to the loss threshold (T_loss) in Equation 5 of the paper.

**Comment by wq1148927746** [comment]
> This value corresponds to the loss threshold (T_loss) in Equation 5 of the paper.

Thanks again for your answer
