### ISSUE TITLE
reproduce problem

### ISSUE THREAD

**Issue by jolt2017** [lucastabelini/PolyLaneNet#44]
Thanks for your contribution. when i try to reproduce the experiment results with tusimple dataset, i found that 1)  the cls_loss is always 0 , is it normal? and the run test.py file with the 500th epoch .pth , it has a low accuracy,.can you give me some advices?
![企业微信截图_16153423778073](https://user-images.githubusercontent.com/45425532/110565392-67fbf400-8189-11eb-86ee-793b4a8432bc.png)
![企业微信截图_16153424394716](https://user-images.githubusercontent.com/45425532/110565440-7ba75a80-8189-11eb-8dfc-5f8406ad38c9.png)

**Comment by lucastabelini** [comment]
The cls_loss is probably just being rounded to zero when printing. In the paper we used 2695 epochs to achieve the reported results. Also, if you do modify the number of epochs, you will have to adjust the learning rate scheduler.

**Comment by jolt2017** [comment]
ok,  thanks for your recommend.
