### ISSUE TITLE
A question about the maximum performance

### ISSUE THREAD

**Issue by cedricgsh** [lucastabelini/PolyLaneNet#46]
Hello. Thank you for your contribution. In table 3, your method achieves a great performance(Acc: 98.03%). I am really interested in it. Can you share the details of the setting of this experiment ? 
@lucastabelini 
![image](https://user-images.githubusercontent.com/33807572/113551848-ea13f700-9627-11eb-9421-1fe97d1c3fa2.png)

**Comment by lucastabelini** [comment]
This experiment is described briefly in the "Polynomial Degree" section:
>  [The experiment] shows the maximum performance (i.e., the upper bound) of methods that represent lane markings as polynomials, measured by fitting polynomials on the test data itself. 

You can reproduce its results with the `utils/upperbound.py` script.

**Comment by cedricgsh** [comment]
Thanks!
