### ISSUE TITLE
A problem about sharing the top-y (h) in lib/models.py line 103

### ISSUE THREAD

**Issue by minghongli233** [lucastabelini/PolyLaneNet#47]
#
    if self.share_top_y:
        # inexistent lanes have -1e-5 as lower
        # i'm just setting it to a high value here so that the .min below works fine
        target_lowers[target_lowers < 0] = 1
        target_lowers[...] = target_lowers.min(dim=1, keepdim=True)[0]
        pred_lowers[...] = pred_lowers[:, 0].reshape(-1, 1).expand(pred.shape[0], pred.shape[1])
I am confused how the code  implements the function of sharing top-y (h). 
The following code seems to extract the lowest point , and share that point.
#          
    target_lowers[...] = target_lowers.min(dim=1, keepdim=True)[0]
And the code below seems to get the value of the first column and expand the other column.  Why consider the first column as the lowest point？
#
        pred_lowers[...] = pred_lowers[:, 0].reshape(-1, 1).expand(pred.shape[0], pred.shape[1])
Thank you very much!

**Comment by lucastabelini** [comment]
```python
    pred_lowers[...] = pred_lowers[:, 0].reshape(-1, 1).expand(pred.shape[0], pred.shape[1])
```
If the top-ys are not shared, one prediction for each lane is made. Else, I ignore the other predictions by copying the prediction for the first lane to the other lanes, in the line shown above. This means that now, semantically, `pred_lowers[:,0]`doesn't  contain the prediction for the first lane, but for all lanes (i.e., the horizon line). There are other ways to implement this, but the one I used was the easiest one at the time.

**Comment by minghongli233** [comment]
Thank you for your reply! 
I aslo want to know why you use the "target_lowers.min" instead of "target_uppers.max". Because, according to the paper,  the "top-y(h)" is be defined as the vertical height of the end of the lane lines. The "top-y(h)" should be obtained by measuring the highest point instead of the lowest point.
# 
    target_lowers[...] = target_lowers.min(dim=1, keepdim=True)[0]

**Comment by lucastabelini** [comment]
The Y values are in image coordinates (i.e., 0 is at the top). Therefore, the minimum of the lower values (`target_lowers`) is the top-y.
