### ISSUE TITLE
The problem of predicting performance

### ISSUE THREAD

**Issue by NARRZ** [lucastabelini/PolyLaneNet#48]
Hello, I used your method to train 2695 epoch, but the test results are not very satisfactory, as shown in the figure below, is this something wrong with me?
![图片](https://user-images.githubusercontent.com/52587607/116531629-f7b05a00-a911-11eb-9cae-fa3681245ec0.png)
![图片](https://user-images.githubusercontent.com/52587607/116531666-03038580-a912-11eb-9279-39ceb83d8660.png)

**Comment by lucastabelini** [comment]
Very difficult for me to know without more information. Did you try testing with the pretrained models provided? For your training, what accuracy was achieved?
