### ISSUE TITLE
Question about sharing the horizon

### ISSUE THREAD

**Issue by voldemortX** [lucastabelini/PolyLaneNet#49]
@lucastabelini Hi! Great codes you are providing here! But I have a question.
Is the sharing of horizon between lanes a possible reason for the low upperbound performance (since the labels don't accurately indicate horizon line)? My colleague just tried directly fitting each lane in the TuSimple test set with 2-order/3-order polynomials and got almost 100% accuracy. But in your paper the upperbound is only ~98%.
BTW, the FP & FN in your TABLE 3 seem rather too low for a <98% Acc. I'm not sure where the problem is.

**Comment by lucastabelini** [comment]
> Is the sharing of horizon between lanes a possible reason for the low upperbound performance (since the labels don't accurately indicate horizon line)?

No. There's an ablation study in the paper showing that (Table V).
>  My colleague just tried directly fitting each lane in the TuSimple test set with 2-order/3-order polynomials and got almost 100% accuracy. But in your paper the upperbound is only ~98%.

The script used to compute the upperbound is [publicly available](https://github.com/lucastabelini/PolyLaneNet/blob/master/utils/upperbound.py). You can compare your implementation to ours  to find out where the discrepancy is.
> BTW, the FP & FN in your TABLE 3 seem rather too low for a <98% Acc. I'm not sure where the problem is.

There's no problem. The threshold for a true positive is 85% accuracy (as defined by the benchmark).

**Comment by voldemortX** [comment]
Thanks for the answers! I'm aware that in actual learning, sharing the horizon does not lead to worse performance (it is indeed a natural heuristic), what I mean is the influence on the upperbound, since by comparing your upperbound code with ours (also based on numpy's fitting), that is the only possible diff we found.

**Comment by lucastabelini** [comment]
I see. In that case, I believe it is indeed the limiting factor.

**Comment by voldemortX** [comment]
Thanks a lot for confirming this! I'll close this issue for now.
