### ISSUE TITLE
How to prepare the label for model training?

### ISSUE THREAD

**Issue by Jail0910** [lucastabelini/PolyLaneNet#5]
How to prepare the label for model training?

**Comment by lucastabelini** [comment]
You can either implement a data loader for you dataset, similiar to [the TuSimple one](https://github.com/lucastabelini/PolyLaneNet/blob/master/lib/datasets/tusimple.py) provided, or transform your annotations to the TuSimple format, described [here](https://github.com/TuSimple/tusimple-benchmark/tree/master/doc/lane_detection).

In the one provided, each JSON [here](https://github.com/lucastabelini/PolyLaneNet/blob/ae8df40b32f819ba1ac480ed2c2ad1ccc35013a6/lib/datasets/tusimple.py#L11) will be loaded. Their paths will be joint with the dataset root path. That is, if you pass the argument `root='tusimple'` and the JSON path is `train.json`, it will load the file in `tusimple/train.json` and read the annotations in the aforementioned TuSimple format.

**Comment by Jail0910** [comment]
> You can either implement a data loader for you dataset, similiar to [the TuSimple one](https://github.com/lucastabelini/PolyLaneNet/blob/master/lib/datasets/tusimple.py) provided, or transform your annotations to the TuSimple format, described [here](https://github.com/TuSimple/tusimple-benchmark/tree/master/doc/lane_detection).
> 
> In the one provided, each JSON [here](https://github.com/lucastabelini/PolyLaneNet/blob/ae8df40b32f819ba1ac480ed2c2ad1ccc35013a6/lib/datasets/tusimple.py#L11) will be loaded. Their paths will be joint with the dataset root path. That is, if you pass the argument `root='tusimple'` and the JSON path is `train.json`, it will load the file in `tusimple/train.json` and read the annotations in the aforementioned TuSimple format.

thank u, I have settled it

**Comment by Petros626** [comment]
@Jail0910 how does the transformation to `.json` format works? I've read the linked links, but struggle with the implementation idea.

**Comment by Jail0910** [comment]
你好我已经收到你的邮件，我会尽快回复，谢谢！姜建宇

**Comment by ZSBSB** [comment]
> 如何准备用于模型训练的标签？
您好，我刚开始学习车道线检测，请问这个怎么解决的？
