### ISSUE TITLE
The question about LPD

### ISSUE THREAD

**Issue by cedricgsh** [lucastabelini/PolyLaneNet#50]
@lucastabelini Hi, PloyLaneNet is an amazing work. I find that you employ LPD in your paper, however, I cannot find the code of LPD script. I guess that LPD code is the function `eval_json` in `utils\metric.py`, but I am not quite sure about this. Could you tell me where is the LPD code? 
Thank you very much!

**Comment by lucastabelini** [comment]
The result of the computation is [here](https://github.com/lucastabelini/PolyLaneNet/blob/master/utils/metric.py#L145). To compute the metric, the functions `area_metric` and `area_distance` are used.

**Comment by cedricgsh** [comment]
Thank you very much！
