### ISSUE TITLE
A consultation on the GPU number

### ISSUE THREAD

**Issue by Starboy-at-earth** [lucastabelini/PolyLaneNet#52]
Dear Author:
Could you please tell me whether the code can run on multiple GPU devices during training, without any further laboring by me?

**Comment by Starboy-at-earth** [comment]
@lucastabelini

**Comment by lucastabelini** [comment]
No, not in its current state. However, I believe the only thing you would have to modify is to add something like this line after line 211 of `train.py`:
```python
model = nn.DataParallel(model)
```

For more information, please see [the documentation](https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html).

**Comment by Starboy-at-earth** [comment]
Okay I will give it a try. Thank you for your in-time reply!!!
