### ISSUE TITLE
problem about speed

### ISSUE THREAD

**Issue by xxKomorebixx** [lucastabelini/PolyLaneNet#53]
Sorry, I have one more question. Unlike LANEATT, I did not find another file in polylanenet to test the speed. I got 1008 FPS after running test.py. Should I run another file to test the real speed?

**Comment by lucastabelini** [comment]
No, you can use `test.py`. Did you set the batch size to 1?

**Comment by xxKomorebixx** [comment]
Okay, thank you very much for your patient and detailed answer.
