### ISSUE TITLE
Check param count

### ISSUE THREAD

**Issue by voldemortX** [lucastabelini/PolyLaneNet#54]
@lucastabelini Hi again! I ran a parameter count with thop on PolyLaneNet (EfficientNetB0), and got 0.87M, do you have a official number recorded on this? I'm not sure if thop is correct about EfficientNet, since the mac count is wrong (< 1G).

I copied `speed.py` from LaneATT.

**Comment by lucastabelini** [comment]
It seems `thop` doesn't give accurate results for EfficientNet (you can see on its output that it ignores many kinds of layers). However, there's a [simpler way ](https://stackoverflow.com/questions/49201236/check-the-total-number-of-parameters-in-a-pytorch-model)to get the parameter count:
```
pytorch_total_params = sum(p.numel() for p in model.parameters())
```
This gives me around 4M parameters.

**Comment by voldemortX** [comment]
Thanks! I got it.
