### ISSUE TITLE
What if we do not predict s and h

### ISSUE THREAD

**Issue by Jensen-Su** [lucastabelini/PolyLaneNet#56]
I wonder if the model can fit a polyline `x = a * y**3 + b * y ** 2 + c * y + d` without fitting offset `s` and horizontal line `h`, since the problem seems to be poor-formed.   

Intuitively, at  point ` y = 100pix`,  the equation would be `x = a * 1000000 + b * 10000 + c * 100 + d`.  A tiny perturbation on `a` would introduce a dramatic change in  `x`, which makes it too hard to learn the other parameters `b, c, d`, especially the offset parameter `d`.

So what are the important points  that make the model successfully fit a polyline?

**Comment by lucastabelini** [comment]
I am not sure that I follow. How would you know the limits of the polyline?
