### ISSUE TITLE
h_samples

### ISSUE THREAD

**Issue by liangjxiong** [lucastabelini/PolyLaneNet#57]
Hello! The number of h_samples in my own dataset is 72. Can I run it with your code? If it can be executed, how should I fix your modified code? thank you!

**Comment by lucastabelini** [comment]
If your dataset's annotations are in TuSimple's format, it should not be difficult. You can modify the [default settings](https://github.com/lucastabelini/PolyLaneNet/blob/master/cfgs/tusimple_fulltrain.yaml) to use your data.

**Comment by liangjxiong** [comment]
Can you specify which parameters should be modified? I don't know much about this.

**Comment by liangjxiong** [comment]
Another point is that the maximum number of lane lines in my dataset is 4, and some are less than 4. How should this be solved?

**Comment by liangjxiong** [comment]
I have solved the above problems. I run: Python test py --exp_ name tusimple_ resnet34 --cfg ./ cfgs/tusimple_ resnet34. yaml --epoch 2695。FPS is 947.644. Why is FPS so high? In your paper, FPS is more than 100.

**Comment by lucastabelini** [comment]
I'm not sure. But if the output seems correct, the faster the better :)
