### ISSUE TITLE
poly_weight

### ISSUE THREAD

**Issue by Hank880223** [lucastabelini/PolyLaneNet#58]
Hello, what does the poly_weight parameter mainly do?
If I want to train a polynomial regression of order 4 or 5, will the parameter poly_weight affect the training?

Thank you

**Comment by lucastabelini** [comment]
The `poly_weight` defines the weights for each polynomial component in the loss function, _i.e_., higher weights have a higher impact on the loss.

**Comment by Hank880223** [comment]
I understand it as higher poly_weight, can the predicted lane points be closer to the real lane points?
