### ISSUE TITLE
The result has a bad performance on curve, how to improve it?

### ISSUE THREAD

**Issue by Hun-ger** [lucastabelini/PolyLaneNet#6]

**Comment by lucastabelini** [comment]
A quote from the paper (Section V, "State-of-the-art Comparison" paragraph):

> It is noticeable that PolyLaneNet’s predictions on parts  of  the  lane  marking  closer  the  camera  (where  more details can be seen) are very accurate. Nonetheless, on parts of the lane marking closer to the horizon, the predictions are less accurate. We conjecture that this might be a result of a local minimum, caused by the dataset’s imbalance. Since most lane markings in the dataset can be represented fairly well with 1st order  polynomials  (i.e.,  lines),  the  neural  network  has  a  bias towards  predicting  lines,  thus  the  poor  performance  on  lane markings with accentuated curvature.
