### ISSUE TITLE
Confidence Scores

### ISSUE THREAD

**Issue by iremonur** [lucastabelini/PolyLaneNet#60]
Hi, the confidence scores in the log.txt files in which located in the experiment files (via the Drive link provided) are extremely low (in the range of 0.0 - 0.0005). Is this an expected result? Should not be the confidence scores higher while the loss decreases to approximately 0.005 at the end of the training?

**Comment by lucastabelini** [comment]
The predicted confidence scores are not in the provided `log.txt` files. The `conf` value shown is the loss component related to the confidence score.

**Comment by iremonur** [comment]
Thank you for your response, so what information does the conf score shown in the log.txt files carry? Is this related to training performance? 
And also, I want the model to classify the lanes (solid, dashed, double). Is it possible, and if so, how? 
I would be glad if you help me with this.

**Comment by lucastabelini** [comment]
> Thank you for your response, so what information does the conf score shown in the log.txt files carry? Is this related to training performance?

As stated previously, the `conf` value shown is the loss component related to the confidence score.

> And also, I want the model to classify the lanes (solid, dashed, double). Is it possible, and if so, how?

Yes, it is possible. The [`elas.py`](https://github.com/lucastabelini/PolyLaneNet/blob/master/lib/datasets/elas.py) file is an example on how to load a dataset with classification annotations. You can use it as a base to provide a data loader for your dataset.
