### ISSUE TITLE
About testing on other Dataset

### ISSUE THREAD

**Issue by PhilWallace** [lucastabelini/PolyLaneNet#63]
Hello there, thanks for the great work. I tried the model on tusimple dataset and it works well. However, when I try the model on other dataset (specifically, CULane dataset) not mentioned in the work, it starts to have some strange outputs as the picture below:

![image](https://user-images.githubusercontent.com/37956889/179462478-a344d21e-909f-4a9a-abbf-37c7ff9145d4.png)

However, it seems that the model does detects the lanes, but wrongly predicts the positions. What is strange to me is that the same code works well for tusimple pictures. I've tried resizing the picture before feeding it to the model, but still doesn't work.

Could you give me some advice on how to deal with this problem to make the model work properly on other data? Many thanks.

**Comment by lucastabelini** [comment]
See [these](https://github.com/lucastabelini/PolyLaneNet/issues/2#issuecomment-631152173) [issues](https://github.com/lucastabelini/PolyLaneNet/issues/7#issuecomment-637601687).
