### ISSUE TITLE
A light-weight backbone?

### ISSUE THREAD

**Issue by xindongzhang** [lucastabelini/PolyLaneNet#9]
Thanks for sharing your great job with us. Is it possible to replace the feature extraction backbone with a smaller backbone? Such as MobileNet, ShuffleNet, and SqueezeNet, etc.

**Comment by lucastabelini** [comment]
Yes. In [this](https://github.com/lucastabelini/PolyLaneNet/blob/ae8df40b32f819ba1ac480ed2c2ad1ccc35013a6/lib/models.py#L35) part of the code, the backbone is chosen. As it can be seen, it should be fairly easy to add a new one.

**Comment by xindongzhang** [comment]
> Yes. In [this](https://github.com/lucastabelini/PolyLaneNet/blob/ae8df40b32f819ba1ac480ed2c2ad1ccc35013a6/lib/models.py#L35) part of the code, the backbone is chosen. As it can be seen, it should be fairly easy to add a new one.

Thanks for your reply
